### PR TITLE
Extensions updated

### PR DESCRIPTION
**Pull request by Krazune**
Added some new extensions, removed some duplicates and fixed a missing ".

### CODE REVIEW

**Comment by blavejr** [comment]
There are a few conflicts on this PR can you please fix them.

**Comment by Krazune** [comment]
The conflicts have been resolved.

**Comment by blavejr** [comment]
@Krazune you did a great job but there still seems to be a few minor errors. update you branch with the master and than add your changes to the updated code and I will merge your PR.

**Comment by Krazune** [comment]
It should be working now.

**Pull request merged**
