### PR TITLE
Added Simple Tkinter GUI

### PR DESCRIPTION
**Pull request by VoxelBuster**

### CODE REVIEW

**Comment by blavejr** [comment]
Hey @VoxelBuster Your code looks good, just update it with the latest code and I will merge it. :)
Thanks for the contribution!

**Comment by VoxelBuster** [comment]
I will resolve the conflicts when I get home today.

**Comment by VoxelBuster** [comment]
Done. I had just added some extensions to the lists, all set now.

**Comment by blavejr** [comment]
@VoxelBuster there still seems to be some conflicts. I think you should update your brunch with the latest master and than add your gui code, just to make sure you are not working on old code.

**Comment by blavejr** [comment]
@VoxelBuster I tried to resolve some of the issues, can you take a look, if its working the way you intended let me know and I will merge it, if its not make the needed changes. :)

Thanks again for your effort, I appreciate it very much.

**Comment by VoxelBuster** [comment]
It won't work the same because the script runs main() without input from the user.

**Comment by VoxelBuster** [comment]
Yeah everything else looks fine though. I can't check for sure until I get home.

**Pull request merged**
